# Change these first
owner: centraldevelopers
repo: status-centralplus-io

sites:
  - name: Api
    url: https:/api.centralplus.io
  - name: App
    url: https://app.centralplus.io
  - name: Admin
    url: http://cp.admin.prod.s3-website-us-east-1.amazonaws.com/
  - name: Admin v2
    url: https://admin.centralplus.io

status-website:
  cname: status.centralplus.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Central

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
